sonar.projectKey=ucv-alpha-beta-lab
sonar.organization=Universidad Cesar Vallejo
sonar.projectName=UCV Alpha Beta Lab
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8